const galleryItems = [
    {id: 1, path: 'images/twins-game.jpg', description: 'My wife and I watching Joe Nathan go into the HOF at our first Twins game in August of 2019 before we got married.', likes: 0},
    {id: 2, path: 'images/mila-shoes.jpg', description: "My daughter Mila wearing daddy's shoes. She is a beautiful little girl who has one heck of a personality and loves to be outside.", likes: 0},
    {id: 3, path: 'images/twins-birth.jpg', description: 'The day the twins were born, Madden and Reya McCarthy. My wife did amazing! This was also my first class day at Prime.', likes: 0},
    {id: 4, path: 'images/wedding.jpg', description: 'This was our wedding day at my father-in-laws house down by the river with all her family. Can you tell we got married around Halloween? ', likes: 0},
    {id: 5, path: 'images/brenda.jpg', description: "This is my second mom, Brenda. Can't explain in words what this woman has done for me.", likes: 0},
    {id: 6, path: 'images/mom.jpg', description: 'This is my mom ash she is about to take on the adventure of puting Mila to sleep.', likes: 0},
    {id: 7, path: 'images/dad.jpg', description: 'A nice picture with my father. He used to be taller than me!', likes: 0},
    {id: 8, path: 'images/mila-door.jpg', description: 'Mila is trying to get out the dog door at our old house. She saw the puppies do it.', likes: 0},
    {id: 9, path: 'images/state-fair.jpg', description: 'State Fair at the top of the ferris wheel with my wife and daughter.', likes: 0},
    {id: 10, path: 'images/chip.jpg', description: 'This is Chip and he is always cheerful and loving.', likes: 0},
    {id: 11, path: 'images/taz.jpg', description: 'This is Taz and she will let you rub her stomache all day.', likes: 0},
    {id: 12, path: 'images/roscoe.jpg', description: 'This is Roscoe and he is a sucker for food scraps.', likes: 0},
    {id: 13, path: 'images/remy.jpg', description: 'This is Remy and she bathes in the sun whenever she finds it.', likes: 0},
    {id: 14, path: 'images/all-nephews.jpg', description: "These four good looking dudes are my nephews. They are each so different and very smart. It's fun watching them play sports together.", likes: 0},
    {id: 15, path: 'images/10k.jpg', description: "Mila getting ready to cheer on her dad doing his first 10k. It was cold and she didn't want to be outside for very long." , likes: 0},
    {id: 16, path: 'images/newspaper.jpg', description: 'Made it in the newspaper for football and almost won play of the week for Channel 5 news sports.' , likes: 0},
    {id: 17, path: 'images/jet-car.jpg', description: 'Elko New Market Speedway had a car with a jet engine mounted on the back.', likes: 0},
    {id: 18, path: 'images/wayne-brady.jpg', description: 'Saw Wayne Brady off the Las Vegas strip just hanging out talking to people. It was an old camera. Whose line is it?', likes: 0},
    {id: 19, path: 'images/hidden-beach.jpg', description: "My favorite place along the St. Croix river. It's a hidden beach that no one seems to go to or know about." , likes: 0},
    {id: 20, path: 'images/zoo-shark.jpg', description: "Mila's first trip to the zoo. She saw a big turtle and she pointed at all the monkey's. We saw this big shark and I had to try and get a picture.", likes: 0},
    {id: 21, path: 'images/moose-colorado.jpg', description: 'Saw a moose in Rocky Mountain National Park. Just on the outside of the gate rail. There was a line of cars behind us.', likes: 0},
    {id: 22, path: 'images/grand-lake.jpg', description: 'A beautiful city in Colorado with a campground and many bears. Up in the hills past the town.', likes: 0},
    {id: 23, path: 'images/utah.jpg', description: 'Scenic Route 12 through Utah with the colors reflecting off the landscape.', likes: 0},
    {id: 24, path: 'images/badlands.jpg', description: "The Badlands is one of the weirdest places. It's like an alien planet.", likes: 0},
    {id: 25, path: 'images/bryce-canyon.jpg', description: 'Bryce Canyon National Park in Utah. Another weird landscape, but nice colors.', likes: 0},
    {id: 26, path: 'images/deer-field.jpg', description: 'Just a whole group of deer eating in the field near Chisago City. Never seen that many deer before at one time.', likes: 0},
];

module.exports = galleryItems;